
project_id = "jbtxxlkhiubuzanegtzn"

[functions.handle-new-signup]
verify_jwt = false

[functions.setup-auth-trigger]
verify_jwt = false

[functions.execute_sql]
verify_jwt = false

[functions.connect-onboarding]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false
