
project_id = "jbtxxlkhiubuzanegtzn"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "https://clinipay.co.uk"
additional_redirect_urls = ["https://clinipay.co.uk/reset-password", "http://localhost:3000/reset-password"]

[functions.create-payment-intent]
verify_jwt = true

[functions.connect-onboarding]
verify_jwt = true

[functions.get-stripe-public-key]
verify_jwt = true

[functions.handle-new-signup]
verify_jwt = true

[functions.refund-payment]
verify_jwt = true

[functions.setup-auth-trigger]
verify_jwt = true

[functions.reset-password]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.payment-intent-webhooks]
verify_jwt = false
