
project_id = "jbtxxlkhiubuzanegtzn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.get-stripe-public-key]
verify_jwt = true

[functions.resume-plan-debug]
verify_jwt = true

[functions.payment-intent-webhooks]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false
