
project_id = "jbtxxlkhiubuzanegtzn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = false

[edge_functions]
enabled = true

[functions.connect-onboarding]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.get-stripe-public-key]
verify_jwt = true

[functions.handle-new-signup]
verify_jwt = false

[functions.payment-intent-webhooks]
verify_jwt = false

[functions.process-notification-queue]
verify_jwt = false

[functions.refund-payment]
verify_jwt = true

[functions.reset-password]
verify_jwt = false

[functions.setup-auth-trigger]
verify_jwt = false

[functions.setup-notification-cron]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false

[functions.process-payment-schedule]
verify_jwt = false

[functions.setup-payment-schedule-cron]
verify_jwt = true
