
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbtxxlkhiubuzanegtzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpidHh4bGtoaXVidXphbmVndHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjU3MTIsImV4cCI6MjA1OTcwMTcxMn0.Pe8trGeGMCmJ61zEFbkaPJidKnmxVOWkLExPa-TNn9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Force schema cache refresh by making a dummy call
// This helps resolve issues with cache mismatches between code and database
try {
  // Use Promise.resolve() to properly handle the Promise chain
  Promise.resolve(
    supabase
      .from('payment_links')
      .select('count')
      .limit(1)
      .then(() => {
        console.log('Supabase schema cache refreshed');
      })
      .catch((e) => {
        console.log('Schema refresh attempt failed:', e);
      })
  ).catch((e) => {
    console.log('Schema refresh attempted but failed:', e);
  });
} catch (e) {
  console.log('Failed to refresh schema cache', e);
}
